# ========================================
# TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "eze"
REPORT_FILE = "reports/bandit-report.json"
IGNORED_FILES = [
    "eze/core/enums.py"
]

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt",
    "requirements-dev.txt"
]
NEWER_MAJOR_SEMVERSION_SEVERITY = "medium"
NEWER_MINOR_SEMVERSION_SEVERITY = "none"
NEWER_PATCH_SEMVERSION_SEVERITY = "none"
IGNORE_BELOW_SEVERITY = "low"
REPORT_FILE = "reports/piprot-report.json"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt",
    "requirements-dev.txt"
]
IGNORE_BELOW_SEVERITY = "medium"
REPORT_FILE = "reports/safety-report.json"

[semgrep]
PRINT_TIMING_INFO = false
EXCLUDE = [
    "tests",
    "tests-integration",
    "examples"
]

    [semgrep.python_slow]
    REPORT_FILE = "reports/semgrep-python-full-report.json"
    CONFIGS = [
        "p/ci",
        "p/python",
    ]

    [semgrep.python]
    REPORT_FILE = "reports/semgrep-python-report.json"
    CONFIGS = [
        "p/ci",
        "p/python",
    ]

    [semgrep.docker]
    SOURCE = "Dockerfile"
    CONFIGS = [
        "p/dockerfile",
    ]
    REPORT_FILE = "reports/semgrep-docker-report.json"


[trufflehog]
SOURCE = ["."]
IGNORED_FILES = [
    ".idea",
    "eze_bom.json",
    "eze_report.json",
    "eze_report.sarif",
    "reports",
    "examples",
    ".pytest_cache",
    "tests/__fixtures__/",
    "tests/__snapshots__/",
    "tests/utils/test_git.py"
]
REPORT_FILE = "reports/truffleHog-report.json"

    [trufflehog.ci]
    INCLUDE_FULL_REASON = false

[python-cyclonedx]
REPORT_FILE = "reports/cyclonedx-bom.json"
REQUIREMENTS_FILE = "requirements.txt"





# ========================================
# REPORT CONFIG
# ========================================
[eze]
CONSOLE_ENDPOINT = "https://lff3adj48f.execute-api.eu-west-2.amazonaws.com/staging"

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["python-piprot", "python-bandit", "python-safety", "python-cyclonedx", "semgrep:python", "semgrep:docker", "trufflehog"]
reporters = ["json", "console", "sarif", "bom"]

[scan.ci]
tools = ["python-piprot", "python-bandit", "python-safety", "python-cyclonedx", "semgrep:python", "semgrep:docker", "trufflehog:ci"]
reporters = ["console", "json", "sarif", "bom", "eze"]
