# ========================================
# TOOL CONFIG
# ========================================
[python-bandit]
SOURCE = "src"

[python-piprot]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "low"

[python-safety]
REQUIREMENTS_FILES = [
    "requirements.txt"
]
IGNORE_BELOW_SEVERITY = "medium"

[semgrep]
PRINT_TIMING_INFO = false
CONFIGS = [
    "p/ci",
    "p/python",
]
EXCLUDE = [
    "tests"
]

[trufflehog]
SOURCE = "src/"

[trufflehog.ci]
INCLUDE_FULL_REASON = false

# ========================================
# REPORT CONFIG
# ========================================
[console]
PRINT_SUMMARY_ONLY = false

# ========================================
# SCAN CONFIG
# ========================================
[scan]
tools = ["trufflehog", "python-piprot", "python-bandit", "python-safety", "semgrep"]
reporters = ["console"]

[scan.ci]
tools = ["trufflehog:ci", "python-piprot", "python-bandit", "python-safety", "semgrep"]
reporters = ["console"]
