name: container
on: push
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run eze
      run: |
        chmod ugo+rwx .
        docker pull riversafe/eze-cli:latest
        docker run -t -v "$(pwd)":/data riversafe/eze-cli test
    - name: Upload EZE Reports as Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: eze_reports
        path: |
            ./eze_junit_report.xml
            ./eze_report.json
