name: container
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: riversafe/eze-cli:latest
    steps:  
    - uses: actions/checkout@v2
    - name: What tools
      run: docker run -t riversafe/eze-cli tools list
