name: container
on: push

jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: riversafe/eze-cli:latest
      options: --user root
    steps:  
    - uses: actions/checkout@v2
    - name: What tools
      run: apt install docker-ce && docker run -t riversafe/eze-cli tools list
