name: container
on: push

# jobs:
#   testbox:
#     steps:  
#     - uses: actions/checkout@v2
# #     - name: What tools
# #       run: echo "hello world"
#     runs-on: ubuntu-latest
#     container:
#       image: riversafe/eze-cli:latest
#       options: --user root
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container:
      image: riversafe/eze-cli:latest
      options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
#     - name: Build docker images
#       run: docker pull riversafe/eze-cli:latest
    - name: install deps
      run: apt-get docker
    - name: Run tests
      run: docker run -t -v "$(pwd)":/data riversafe/eze-cli test
