name: container
on: push
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT}}
      
    - name: run dockerfile
      uses: ./
#       run: |
#         chmod ugo+rwx .
#         docker pull riversafe/eze-cli:latest
#         docker run -t -v "$(pwd)":/data riversafe/eze-cli test
    - name: find locations
      run: |
        cd reports/python
        ls -a
    - name: Upload EZE Reports as Artifact'
      uses: actions/upload-artifact@v2
      with:
         name: eze_reports
         path: |
             ./reports/python/eze_junit_report.xml
             ./reports/python/eze_report.json
